name: Build Android APK

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch: # 支持在 GitHub 界面上手动点击按钮触发编译

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up pre-installed JDK 11
      run: |
        echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
        echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH

    - name: Build with Gradle
      run: gradle assembleDebug --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: DianshijiaLite-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
